Style the components
Zel-hub7/book-store pull request #6
Opened 2023-08-25 13:44 UTC by Zel-hub7

1. I styled all the components.
2. I made sure that it aligns with the design.
3. I made sure that there are no linter errors.

2023-08-25 14:33 UTC, skyv26 requested changes
## Hi @Zel-hub7, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZDMzYmY2ZWU0MmEwMTJjZTczMGVhNDhlM2E2NWViYmQ0YzY5ZTBiNiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/17FxSFyYNOgThnonDK/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 

## Required Changes ♻️

- [ ] **Kindly always double-check your work before asking for a review, because as soon as I cloned your project and tried to run the server I got some errors related to typos in your project. Your project does contain the folder `Components` not the *components* because of this typo your application was breaking, either rename your `Components` back to Components or make the changes in your other files and folder structure that you did in the previous milestone. Please verify your project by running the server**.

### References

#### Your Folder name
![Screenshot from 2023-08-25 20-01-13](https://github.com/Zel-hub7/book-store/assets/66476329/080ae947-ee75-4216-8e74-741ae5ded964)

#### Files you imported
![Screenshot from 2023-08-25 19-56-43](https://github.com/Zel-hub7/book-store/assets/66476329/d68023b7-6e64-4a7b-9af4-b9c2270d2efe)

![Screenshot from 2023-08-25 19-56-23](https://github.com/Zel-hub7/book-store/assets/66476329/9eacccd2-74c9-49f8-a2e9-81b8db69ff19)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 14:33 UTC, skyv26 commented on src/Components/styles/BookComp.css
> +  /*  stylelint-disable-next-line */
- [ ] Please don't disable the style linter error instead try to find the reason behind getting the error, because it is very important to have a good knowledge about the errors, so that in future when you will do work for the companies you should be able to know how to solve the things quickly.

2023-08-25 14:33 UTC, skyv26 commented on src/Components/styles/Form.css
> +.form-container {
- [ ] Kindly adhere to the project requirement because as I can see your design especially the input fields does not match precisely with the **Zeplin** design, which makes your design `inconsistent` and looks unprofessional. Please have a look at the attached image and table and make sure that you are using the right font family, spacing and padding to make your design exactly look like the original design.

### Requirement
![Screenshot from 2023-08-25 19-39-00](https://github.com/Zel-hub7/book-store/assets/66476329/25817c6d-7c5c-4448-86b5-87ab53bbb20d)

### Design Comparison
<table>
<tr>
<th>Zeplin Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![image](https://github.com/Zel-hub7/book-store/assets/66476329/6d9ec55e-266a-425d-a203-1b0203355411)

</td>
<td>

![Screenshot from 2023-08-25 19-39-18](https://github.com/Zel-hub7/book-store/assets/66476329/26e0f404-4b1b-4ce6-97dc-d4cc8fa4ff47)

</td>
</tr>
</table>

2023-08-25 14:33 UTC, skyv26 commented on src/Components/styles/navBar.css
> +}
- [ ] Kindly adhere to the project requirement because as I can see your navigation menu's styles do not match precisely with the **Zeplin** design, which makes your design `inconsistent` and looks unprofessional. Please have a look at the attached image and table and make sure that you are using the right font family or font weight or spacing and padding to make your design exactly look like the original design.

### Requirement
![Screenshot from 2023-08-25 19-39-00](https://github.com/Zel-hub7/book-store/assets/66476329/25817c6d-7c5c-4448-86b5-87ab53bbb20d)

### Design Comparison
<table>
<tr>
<th>Zeplin Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![Screenshot from 2023-08-25 19-41-00](https://github.com/Zel-hub7/book-store/assets/66476329/bdcbd462-1495-4408-bc75-22bb1fda1c77)

</td>
<td>

![Screenshot from 2023-08-25 19-40-49](https://github.com/Zel-hub7/book-store/assets/66476329/e668be1c-f1f0-47e7-8048-f6589e7ae402)

</td>
</tr>
</table>

2023-08-25 15:01 UTC, Zel-hub7 commented on src/Components/styles/Form.css
> +.form-container {
Kindly always double-check your work before asking for a change because in the requirement when we start the project you can clearly see that we are asked to change the category input to author.

![reviewer](https://github.com/Zel-hub7/book-store/assets/101441573/bbd182be-4539-47f0-8c52-5cb77f2a1cf9)

2023-08-25 17:11 UTC, skyv26 commented on src/Components/styles/Form.css
> +.form-container {
@Zel-hub7 As your wish, best of luck 👍🏻

2023-08-26 08:23 UTC, andersonlebon approved these changes
## Hi @Zel-hub7 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)
: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-26 08:27 UTC, merged